### PR TITLE
Feature/send analytics

### PR DESCRIPTION
**Pull request by dHRUSHIT**
adding flag : sendAsAnalytics for sending analytics data when the user navigates away to another page using fetch with 'keepalive' flag true

Reason for the addition:
sending the data without 'keepalive' flagged fetch is not possible as the browser tends to ignore the async call generated and cancels it. Setting the flag will tell the browser not to wait for the response but to send the request anyway.

Reason for conditionally setting the 'keepalive' flag:
'keepalive' comes with limitations as mentioned here: https://javascript.info/fetch-api#keepalive.
> It does not allow any ACTIVE request to be over 64kb.
> Server response cannot be handled as the browser is already unloaded in the mean time.

### CODE REVIEW

**Comment by VivekFitkariwala** [comment]
Can you fix merge conflicts

**Comment by dHRUSHIT** [comment]
Hey @VivekFitkariwala , cleared the merge conflicts.

Thanks.

**Comment by VivekFitkariwala** [comment]
Have you updated bundle.js?

**Comment by dHRUSHIT** [comment]
Hi @VivekFitkariwala 

I was not aware about pushing the files in dist folder. I thought it would be taken care of by CICD.

I have updated the bundle file now.

Please check now.

Thanks

**Pull request merged**
